proxy_cache_path /var/cache/nginx/remote
    levels=1:2
    keys_zone=remote-cache:100m
    inactive=30d
    max_size=20g;

proxy_cache_path /var/cache/nginx/tileserver
    levels=1:2
    keys_zone=tileserver-cache:50m
    inactive=30d
    max_size=1g;

server {
    listen       8081;
    listen  [::]:8081;

    location /maps {
        proxy_pass https://${NGINX_RASTER_TILE_HOST}/maps;

        proxy_ssl_server_name on;
        proxy_ssl_name ${NGINX_RASTER_TILE_HOST};

        proxy_set_header Host ${NGINX_RASTER_TILE_HOST};

        valid_referers none blocked ${NGINX_RASTER_REFERER_HOST};
        if ($invalid_referer) {
            return 403;
        }
        proxy_set_header Referer $http_referer;

        expires 1d;
        add_header Cache-Control "public";

        proxy_cache remote-cache;
        proxy_cache_valid 200 204 7d;
        proxy_cache_valid 404 1m;
        proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
        proxy_cache_lock on;
    }

    location / {
        proxy_pass http://tileserver-gl:8080;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        expires 1d;
        add_header Cache-Control "public";

        proxy_cache tileserver-cache;
        proxy_cache_valid 200 204 1d;
        proxy_cache_valid 404 1m;
        proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
        proxy_cache_lock on;
    }
}
